"""Wire types for the Agent Host Protocol (AHP).

This package mirrors ``ahp-types`` (Rust) / ``ahptypes`` (Go) /
``@microsoft/agent-host-protocol``'s type surface (TypeScript): plain data models
with no I/O, safe to import from both the client and the reducers.
"""

from .actions import (
    AnnotationAddedAction,
    AnnotationRemovedAction,
    ChangesetOperationStatusChangedAction,
    ChatAction,
    ChatConfirmationRequestedAction,
    ChatTurnCompletedAction,
    ChatTurnContentRefAddedAction,
    ChatTurnDeltaAction,
    ChatTurnStartedAction,
    RootAction,
    RootAgentsChangedAction,
    RootSessionAddedAction,
    RootSessionRemovedAction,
    SessionAction,
    SessionChatAddedAction,
    SessionDisposedAction,
    SessionTerminalAddedAction,
    SessionTitleChangedAction,
    StateAction,
    TerminalAction,
    TerminalExitedAction,
    TerminalOutputAction,
)
from .commands import COMMANDS
from .common import (
    URI,
    ActionEnvelope,
    ActionOrigin,
    AhpModel,
    ClientCapabilities,
    ClientSeq,
    ContentRef,
    ErrorInfo,
    HostCapabilities,
    ProtocolVersion,
    ServerSeq,
    Snapshot,
)
from .errors import AhpError, AhpErrorCode, JsonRpcErrorCode, JsonRpcErrorObject
from .jsonrpc import (
    JsonRpcNotification,
    JsonRpcRequest,
    JsonRpcResponse,
    JsonRpcResponseError,
    JsonRpcResponseSuccess,
    ProtocolMessage,
    RequestId,
    parse_protocol_message,
)
from .notifications import (
    NOTIFICATIONS,
    ActionNotification,
    AuthRequiredNotification,
    OtlpLogNotification,
    SessionAddedNotification,
    SessionRemovedNotification,
)
from .state import (
    AgentInfo,
    AnnotationsState,
    AnyChannelState,
    ChangesetOperationStatus,
    ChangesetState,
    ChatState,
    RootState,
    SessionState,
    TerminalState,
    TerminalStatus,
    Turn,
    TurnRole,
    TurnStatus,
    VersionedState,
)

__all__ = [
    # common
    "URI",
    "ActionEnvelope",
    "ActionOrigin",
    "AhpModel",
    "ClientCapabilities",
    "ClientSeq",
    "ContentRef",
    "ErrorInfo",
    "HostCapabilities",
    "ProtocolVersion",
    "ServerSeq",
    "Snapshot",
    # errors
    "AhpError",
    "AhpErrorCode",
    "JsonRpcErrorCode",
    "JsonRpcErrorObject",
    # jsonrpc
    "JsonRpcNotification",
    "JsonRpcRequest",
    "JsonRpcResponse",
    "JsonRpcResponseError",
    "JsonRpcResponseSuccess",
    "ProtocolMessage",
    "RequestId",
    "parse_protocol_message",
    # state
    "AgentInfo",
    "AnnotationsState",
    "AnyChannelState",
    "ChangesetOperationStatus",
    "ChangesetState",
    "ChatState",
    "RootState",
    "SessionState",
    "TerminalState",
    "TerminalStatus",
    "Turn",
    "TurnRole",
    "TurnStatus",
    "VersionedState",
    # actions
    "AnnotationAddedAction",
    "AnnotationRemovedAction",
    "ChangesetOperationStatusChangedAction",
    "ChatAction",
    "ChatConfirmationRequestedAction",
    "ChatTurnCompletedAction",
    "ChatTurnContentRefAddedAction",
    "ChatTurnDeltaAction",
    "ChatTurnStartedAction",
    "RootAction",
    "RootAgentsChangedAction",
    "RootSessionAddedAction",
    "RootSessionRemovedAction",
    "SessionAction",
    "SessionChatAddedAction",
    "SessionDisposedAction",
    "SessionTerminalAddedAction",
    "SessionTitleChangedAction",
    "StateAction",
    "TerminalAction",
    "TerminalExitedAction",
    "TerminalOutputAction",
    # notifications
    "NOTIFICATIONS",
    "ActionNotification",
    "AuthRequiredNotification",
    "OtlpLogNotification",
    "SessionAddedNotification",
    "SessionRemovedNotification",
    # commands
    "COMMANDS",
]
